# Generated by Django 5.2.13 on 2026-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_drop_legacy_arriere_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_activite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='code_echeance',
            field=models.IntegerField(default=0),
        ),
    ]
