# Generated by Django 5.2.13 on 2026-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_code_activite_code_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant_derniere_facture',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
